spring:
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:schema
    username: sa
    password: password
    driverClassName: org.h2.Driver
  sql:
    init:
      platform: h2
